<div role="tabpanel" class="tab-pane active box box-primary" id="about">
	<h2>About Us</h2>								
	<p>
		<span class="text-bold">Occupying 2.39% of India’s landmass, Assam is the most vibrant of eight states comprising the Northeast. Bounded by these states, West Bengal, Bhutan and Bangladesh, its topographical asymmetry is underscored by the Barail hill range sandwiched between two valleys – Brahmaputra and Barak – named after the dominant rivers.
		<br/>Assam is synonymous with breathtaking natural beauty, teeming wildlife, immaculate tea gardens and warm, beautiful people.It’s strategic location in the northeast of India, and it’s accessibility from the rest of the country makes it the gateway to the northeastern states.Green is the predominant colour of the state with an impressive 35% forest cover and thousands of hectares under tea cultivatation.</span>
		<br/><br/>Assam has five national parks including the World Heritage Sites of Kaziranga and Manas, and 20 Wildlife sanctuaries. The great Indian one-horned rhinocerous is one of Assam's most famous denizens.Over the centuries, people of various ethnic, religious and linguistic backgrounds have been attracted to the fertile valleys of Assam making it a mosiac of various cultures.
		<br/>It is no wonder then that Assam is said to be like a miniature version of the whole country itself. Supporting the state's abundant wildlife and luscious vegetation are the monsoons which stretch from late May to September, but there are intermittent rains even in the winters. Winters begin in late November and continue till February.
		<br/>Winter mornings in most parts of Assam are marked by dense fog giving the land an aura of ethereal beauty.The Brahmaputra Valley is an alluvial plain about 724 kms in length and 81 kms in breadth. It is enclosed on the north by the mighty Himalayas, south by the Garo, Khasi, Jaintia and Naga Hills. The Brahmaputra, the lifeline of the valley which shares it's name, floods the nearby land with fertile silt every year to ensure a rich harvest.To the south of the valley are the charming hills of Karbi Anglong. Further south are the North Cachar Hills.Located here, amidst beutiful orchards, is Assam's only hill station, Haflong. The southern part of Assam is the Barak Valley, which derives its name from the Barak river. This region is a treasure trove of untouched natural beauty.Brahmaputra, Barak and their 120 tributaries ensure a fertile land dotted with more than 3,500 wetlands, 800 expansive tea estates and 25 major wildlife preserves housing rare species of flora and fauna.
	</p>
	
	</ul>
</div>