<div role="tabpanel" class="tab-pane box box-primary" id="ip">
	<h2>Inspection Procedure</h2>		
	<h4><strong>Inspection on submission of application.</strong></h4>
	<p>First  inspection  shall  be  made  within  seven  days  following  receipt  of  application  during  which  the  Authority  through  its  own  officials  or  hired  agency  shall  examine  that  plan submitted complies with the requirement of these rules.</p>
	<h2>Inspection Guidelines</h2>		
	<ol>
		<li>Should  the  Authority  determine  at  any  stage  that the  construction  is  not  proceeding according to the sanctioned plan or is in violation of any of the provisions of these rules, it  shall  notify  the  permit  holder  and  all  further  construction  shall  be  stopped  until correction has been  effected and approved by  the Authority. If the permit  holder fails to comply with the requirements at any stage of construction, the Authority is empowered to cancel the building permit issued. </li>
		<li>The  Authority  may  either  sanction  or  refuse  sanction  to  the  plans  and  specifications  or may  sanction  them  with  such  modification  or  directions  as  it  may  deem  necessary  and there upon shall communicate its decision to the person giving the notice in the prescribed Forms at 3 and 4. </li>
		<li>The  Authority  shall  issue  permit  for  the  building  plans,  on  recommendation  from  the District Fire Officer, for the buildings requiring the scrutiny of the District Fire Officer. </li>
		<li>If within 60 days of the receipt of notice as mentioned in these rules, the Authority fails to intimate in writing to the person who has given the notice, of its refusal or sanction to the notice with its plans and statements, the same shall be deemed to be sanctioned, provided that the building plan conforms to the provisions laid down in these rules. The intention of proceeding for construction should be brought to the notice of the authority in writing by  the  person  who  has  given  notice.  On  expiry  of  15 days  of  giving  such  notice  to  the Authority  and  having  not  received  any  intimation,  the  applicant  may  proceed  with  the construction. However, nothing shall be construed to authorize any person to do anything in contravention or against the terms of the lease or title of the land or against any rules or Regulations, operating at the time of execution of the work at site. </li>
		<li> Once the plan has been scrutinized and objections have been pointed out, the  owner who has  been given  the  notice  under  these  rules  shall  modify  the  plan  to  comply  with  the 27 objections raised and  resubmit  the  modified  plans. The  Authority  shall  scrutinize  the resubmitted  plans  and  if, there  are  still  some  objections  that  shall  be  intimated  to  the applicant for compliance. Only thereafter the plan shall be sanctioned.</li>
		<li>The owner and registered technical persons shall be individually and severally responsible for any violation of Master Plan / Zonal Plan / Building rules, architectural controls, lease deed  conditions  etc.  In  case  of  any  default  they  shall  be  liable  for  penal  action.  Any construction so raised shall be deemed to be unauthorized. </li>
	</ol>
</div>