<div role="tabpanel" class="tab-pane box box-primary" id="time">
	<h2>Time Limits</h2>		
	<table class="table table-responsive">
		<tr>
			<td width="800.00em">APPLICATION FOR REGISTRATION OF ESTABLISHMENT UNDER THE ASSAM SHOPS & ESTABLISHMENT ACT,1971 IN FORM 'O' UNDER SECTION 36 AND RULE 45 OF THE ASSAM RULES.</td>
			<td colspan="3" align="center">Time limit is 7 days</td>
		</tr>
		<tr>
			<td>APPLICATION FOR REGISTRATION OF ESTABLISHMENT AS THE PRINCIPAL EMPLOYER IN ' FORM I ' UNDER SECTION 7 OF THE CONTRACT LABOUR (R & A)ACT, 1970 AND RULE 17 (1) OF THE ASSAM RULES.</td>
		</tr>
		<tr>
		    <td>APPLICATION FOR LICENCE OF A CONTRACTOR(S) FOR RECRUITMENT OF MIGRANT WORKMAN IN 'FORM IV' UNDER SECTION 8(1)(A) OF THE INTERSTATE MIGRANT WORKMEN (R.E. & C.S.) ACT, 1979 AND RULE 7 (1)OF THE ASSAM RULES.</td></tr>
		<tr>
			<td>APPLICATION FOR REGISTRATION OF ESTABLISHMENT AS THE PRINCIPAL EMPLOYER IN ' FORM I ' UNDER SECTION 4 OF THE INTERSTATE MIGRANT WORKMEN (R.E & C.S)ACT, 1979 AND RULE 3 (1) OF THE ASSAM RULES</td>
			<td colspan="7" align="center">Time limit is 15 days</td>
		</tr>
		<tr>
			<td>aPPLICATION FOR REGISTRATION OF PLANTATIONS AND GRANT OF CERTIFICATES OF REGISTRATION IN 'FORM 13' UNDER SECTION 3-B OF THE PLANTATIONS LABOUR (AMENDMENT) ACT, 1981 AND RULE 2-A OF THEASSAM RULES</td>
		</tr>
		<tr>
			<td>APPLICATION FOR REGISTRATION OF ESTABLISHMENT IN 'FORM I' UNDER SECTION 7 OF THE BUILDING & OTHER CONSTRUCTION WORKERS (R.E & C.S) ACT, 1996 AND RULE 23(1) OF THE ASSAM RULES, 2007</td>
		</tr>
		<tr>
			<td>APPLICATION FOR LICENSE OF A CONTRACTOR(S) IN 'FORM IV' UNDER SECTION 12 OF THE CONTRACT LABOUR (R & A)ACT,1970 AND RULE 21 (1) OF THE ASSAM RULES</td>
		</tr>
		<tr>
			<td>APPLICATION FOR LICENCE OF A CONTRACTOR(S) FOR EMPLOYMENT OF MIGRANT WORKMAN IN 'FORM V' UNDER SECTION 8(1)(B) OF THE INTERSTATE MIGRANT WORKMEN (R.E. & C.S.) ACT,1979 AND RULE 7 (2)OF THE ASSAM RULES</td>
		</tr>
		<tr>
			<td>APPLICATION FOR RENEWAL OF THE CERTIFICATE OF REGISTRATION OF ESTABLISHMENT IN FORM 'O' UNDER SECTION 36 OF THE ASSAM SHOPS & ESTABLISHMENT ACT, 1971AND RULE 49 OF THE ASSAM RULES.</td>
		</tr>
		<tr>
			<td>APPLICATION FOR RENEWAL OF LICENSE IN FORM VII UNDER RULE 29 (2) OF THE CONTRACT LABOUR (R & A) RULES, 1971</td>
		</tr>
		<tr>
			<td>APPLICATION FOR RENEWAL OF LICENSE IN FORM IX UNDER RULE 14(2) OF THE INTERSTATE MIGRANT WORKMEN (R.E. & C.S) ASSAM RULES, 1981</td>
		</tr>
	</table>
</div>