<div role="tabpanel" class="tab-pane box box-primary" id="tpsc">
	<h2>Third Party/ Self Certification</h2>		
	<p>Subject to approval of the Board, Pollution Control Board, Assam intends to initiate Auto renewal of 'Consent to Operate' for Green Category of industries which will submit a self-certification on compliance of Environment Regulations. The strategies for effective implementation of environmental regulations include enforcement and compliance aspects which are being handled simultaneously with the consent.</p>
	<p>In order to expedite the consent, it is now proposed to emphasis enforcement and compliance as discrete activities along with the responsiblity of declaring the compliance of regulations by the industry while seeking renewal of consent. Initially thr proposed scheme of auto-renewal of consent based on self-certification and Commitment letter will be rolled out for the Green categories of industries.</p>
	<h4>The key features of this scheme are as follows:</h4>
	<ol>
		<li>The auto-renewal of consent will be applicable when there is no increase in overall production capacity and also in pollution load.</li>
		<li>This scheme is applicable, only in case if there is marginal increase (upto max 10%) in the capital investment which is due to infrastructure development, clean technology, pollution control system and better production management, without increase in production or pollution load, the industry shall submit corresponding fees for Consent to Establish and also difference in consent to operate fees since the blocks year the capital investment is made on pro-data basis.</li>
		<li>In case, if there is if there is increase in Capital investment by over  10% then the application for grant of renewal of Consent under Auto-renewal Policy will not be considered. The industry needs to apply in prescribed application form.</li>
		<li>In case, if the capital investment is decreased, then the application for grant of renewal of Consent under Auto-renewal Policy will not be considered. The industry needs to apply in prescribed application form.</li>
		<li>For the Auto-renewal, industry shall submit format of Self-Certification  (Annexure ‘A’) on compliance of earlier Consent conditions duly signed by person authorised by Company’s Board and shall submit the copy of the said Resolution (Annexure ‘C’) along with the prescribed fees at PCBA HO/Ros and, also industry shall submit Commitment towards compliance of the Consent conditions & the Environmental Laws in prescribed format (Annexure-‘B’).</li>
		<li>The format of self-certification by industries is enclosed as Annexure ‘A’ will be available in the Board;s website. The industry shall submit this format along with the prescribed fees either at PCBA Head Office or respective Regional Offices(Ros) or through online under EoDB web portal. In case, the application is submitted at Ros, Ros shall ensure that the same shall be forwarded within 7 days along with details of fees paid. The renewal will be reflected in the EoDB web portal within 15 days.</li>
	</ol>
	<p>For more information please refer here  PDF <a href="<?php echo $server_url;?>dept_documents/pcb/Third Party& Self Certification/PDF files.pdf" target="blank" >files.pdf</a></p>
</div>