<div role="tabpanel" class="tab-pane active box box-primary" id="about">
	<h2>About Us</h2>								
	<p>The Department of Environment and Forests, Government of Assam is a department under the Government of Assam. Its mission is to protect and improve the environment, safeguard the forests and wildlife of the State, preserve and add new dimensions to the rich heritage of our composite culture, protect and improve the natural environment, and to have compassion for living creatures.  It also encompasses opening up the forestry sector for income and employment generation among our people while conserving the priceless biodiversity of the State. </p>
	<p>Forests of Assam have rich biodiversity of flora and fauna. It has a wide range of forests viz. Evergreen and Semi Evergreen forests, Mixed Deciduous forests, Sal forests, Riverine forests, Moist Savannah, Dry Savanna and Dry Miscellaneous type of forests. Managing these vast natural and life sustaining ecosystems is a herculean task in itself. The State Government accords top most priority for the conservation of these diverse ecosystems while keeping the needs and aspirations of the people into consideration and remembering that we owe this for the future generations.</p>
	<h4><strong>Policy:</strong></h4>
	<p>Forest resources have been regulated since early times. The roots of legislations, policies and guide lines for natural resource management in India can be traced back to the days of British colonialism. The relevant constitutional framework at the backdrop of management of forest resources are enumerated as follow</p>
	<ul>
		<li><strong>Forest Policy,Govt. of India-</strong>In 1952, the erstwhile Ministry of Food and Agriculture, Government of India enunciated a Forest policy to be followed in the management of state forests in the country. The need for this Policy was to highlight the changes since the enunciation of the Forest policy of 1894. Forest, however. continued to be viewed as source of revenue. While recognizing that the proportion of land to be kept permanently under forest would naturally vary in different regions, the policy said that practical consideration suggests, "that India, as whole, would aim at maintaining one third of its total land area under forests." Emphasis was laid on the conversion of low value mixed forests to high value plantation of commercial species.</li>
		<li><strong>Bamboo Policy-</strong>Bamboo and Rattan represent untapped major resource of Assam State whose full ecological and economic potential needs to be recognized, developed and promoted in a manner ensuring ecological security for all round sustainable development of the State and also the livelihood security to its people.</li>
	</ul>
</div>